# Numpy to Pytorch

### Introduction

In this lesson, we'll begin moving towards the Pytorch library.  We'll see how we can build linear layers in Pytorch as well as make use of non-linear layers.  Let's get started.

### Initializing a Model

Previously, we've initialized a new model with something like the following.

In [1]:
def init_model(n_features, neur_l1, neur_out):
    W1 = np.random.randn(n_features, neur_l1) / np.sqrt(n_features)
    b1 = np.zeros((1, neur_l1))
    W2 = np.random.randn(neur_l1, neur_out) / np.sqrt(neur_l1)
    b2 = np.zeros((1, neur_out))
    model = {'W1': W1, 'b1': b1, 'W2': W2, 'b2': b2}
    return model

In [2]:
import torch

In [6]:
import numpy as np
A = np.random.randn(5, 3)
B = np.random.randn(3, 4)

In [8]:
A @ B

array([[-1.28608601, -1.32188029,  0.69852584, -1.14986886],
       [ 2.72627615,  0.95844272,  0.46377418,  5.63486948],
       [-1.28759655, -0.95205668,  0.36545575, -2.02623457],
       [-5.18368053, -2.898354  , -0.45369021, -6.02356844],
       [-4.1142123 , -1.29720781, -1.79189306, -5.02665616]])

In [9]:
# torch.zeros(5, 3)

A_torch = torch.randn(5, 3)
B_torch = torch.randn(3, 5)

In [11]:
A_torch @ (B_torch)

tensor([[ 0.9327, -0.0278,  2.0258,  0.4853,  0.9474],
        [-0.1244,  0.3464,  0.8230,  0.1596,  0.2478],
        [ 0.9598,  0.1267,  2.8164,  1.1920,  2.0701],
        [ 1.0406, -0.4123,  1.1772,  0.6250,  1.1625],
        [-1.8487,  0.5782, -2.2509, -0.3788, -0.9299]])

In [13]:
W1 = torch.randn(784, 64) 
b1 = torch.randn(64) 

In [17]:
# W1.view(-1)

In [19]:
from torch import nn

fc1 = nn.Linear(784, 64)

In [28]:
X =  torch.randn(100, 784)

In [34]:
(X @ fc1.weight.T + fc1.bias)

tensor([[-1.7982,  0.1649, -0.4013,  ...,  0.6185,  0.2122, -0.7684],
        [-0.3963, -0.3520,  0.5135,  ..., -0.0484, -1.0442, -0.1940],
        [-0.6166, -0.2651,  0.2134,  ...,  1.5000, -0.7126,  0.8592],
        ...,
        [ 0.1554, -0.3180,  0.1073,  ..., -1.0696, -0.2473, -0.0074],
        [-0.8113,  0.6377,  0.1044,  ..., -0.7322, -0.1972,  0.0618],
        [ 1.1190, -0.9516, -0.2273,  ...,  0.3510,  0.3763, -0.3176]],
       grad_fn=<AddBackward0>)

In [37]:
fc1(X)

tensor([[-1.7982,  0.1649, -0.4013,  ...,  0.6185,  0.2122, -0.7684],
        [-0.3963, -0.3520,  0.5135,  ..., -0.0484, -1.0442, -0.1940],
        [-0.6166, -0.2651,  0.2134,  ...,  1.5000, -0.7126,  0.8592],
        ...,
        [ 0.1554, -0.3180,  0.1073,  ..., -1.0696, -0.2473, -0.0074],
        [-0.8113,  0.6377,  0.1044,  ..., -0.7322, -0.1972,  0.0618],
        [ 1.1190, -0.9516, -0.2273,  ...,  0.3510,  0.3763, -0.3176]],
       grad_fn=<AddmmBackward>)

In [40]:
# class Module:
#     def __init__(self):
        

In [62]:
# ??nn.Module

import torch.nn.functional as F

In [73]:
linear = nn.Linear(784, 64)

In [78]:
# linear.weight, linear.bias

In [79]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.W1 = nn.Linear(784, 64)
        self.W2 = nn.Linear(64, 64)
        self.W3 = nn.Linear(64, 64)
        self.W4 = nn.Linear(64, 10)
        
    def forward(self, X):
        Z1 = self.W1(X)
        A1 = torch.sigmoid(Z1)
        Z2 = self.W2(A1)
        A2 = torch.sigmoid(Z2)
        Z3 = self.W3(A2)
        A3 = torch.sigmoid(Z3)
        Z4 = self.W4(A3)
        return F.log_softmax(Z4, dim = 1)

In [70]:
neural_net = Net()
neural_net

Net(
  (W1): Linear(in_features=784, out_features=64, bias=True)
  (W2): Linear(in_features=64, out_features=64, bias=True)
  (W3): Linear(in_features=64, out_features=64, bias=True)
  (W4): Linear(in_features=64, out_features=10, bias=True)
)

In [84]:
# 6*(torch.tensor([1, 2]))


tensor([ 6, 12])

In [71]:
X = torch.randn(100, 784)

In [72]:
neural_net(X)

tensor([[-2.3801, -2.1525, -2.1782, -2.2217, -2.1163, -2.3503, -2.3163, -2.5885,
         -2.6359, -2.2224],
        [-2.3811, -2.1522, -2.1782, -2.2208, -2.1160, -2.3489, -2.3160, -2.5907,
         -2.6343, -2.2241],
        [-2.3795, -2.1537, -2.1773, -2.2208, -2.1149, -2.3516, -2.3154, -2.5896,
         -2.6345, -2.2248],
        [-2.3812, -2.1533, -2.1767, -2.2221, -2.1144, -2.3483, -2.3152, -2.5897,
         -2.6363, -2.2255],
        [-2.3788, -2.1514, -2.1783, -2.2165, -2.1148, -2.3527, -2.3169, -2.5912,
         -2.6368, -2.2264],
        [-2.3782, -2.1536, -2.1760, -2.2212, -2.1157, -2.3526, -2.3148, -2.5896,
         -2.6367, -2.2243],
        [-2.3784, -2.1528, -2.1768, -2.2201, -2.1173, -2.3510, -2.3165, -2.5888,
         -2.6372, -2.2236],
        [-2.3809, -2.1524, -2.1776, -2.2196, -2.1132, -2.3533, -2.3155, -2.5898,
         -2.6360, -2.2249],
        [-2.3799, -2.1517, -2.1789, -2.2201, -2.1139, -2.3517, -2.3155, -2.5893,
         -2.6359, -2.2259],
        [-2.3785, -

In [ ]:
# .0005*

We initialized a set of weight matrices (`W1`, and `W2`) and bias vectors (`b1` and `b2`), which we later tune through our training procedure.  Once these weights and biases are trained, we can use them to make a prediction with our model.

With Pytorch, we can do the same thing with a Pytorch tensor. 

In [37]:
import torch

W1 = torch.randn(8, 784)

In [40]:
W1

tensor([[-1.1513, -0.0768, -0.3163,  ..., -1.3084, -0.2952, -1.2212],
        [ 0.5460,  0.0042,  1.0023,  ...,  1.1528,  0.1197,  0.0430],
        [ 0.4627, -1.6576, -2.6115,  ...,  0.6369, -1.8958,  1.0517],
        ...,
        [ 0.4963, -0.0175,  0.3728,  ..., -2.6316,  0.1751,  0.4416],
        [ 0.6346,  1.1451,  0.7053,  ...,  0.6085,  0.0940, -1.5013],
        [-0.2043,  1.0081,  0.3093,  ..., -1.3962,  0.3015,  0.8347]])

In [39]:
W1.shape

torch.Size([8, 784])

As we can see, the Pytorch library provides us with much of the same interface as numpy.  We can initialize data through the `randn` function, the `randint` function, or by creating our own custom array just like in numpy.

In [41]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

And we can select our data by using the same bracket operators as we saw in numpy.

In [43]:
W1[:2, :3]

tensor([[-1.1513, -0.0768, -0.3163],
        [ 0.5460,  0.0042,  1.0023]])

The main difference between a pytorch tensor and a numpy array that we need to worry about at this point is reshaping our data.  In Pytorch, the method for changing the shape of the data is called `view`.

In [47]:
W1.view(-1)

tensor([-1.1513, -0.0768, -0.3163,  ..., -1.3962,  0.3015,  0.8347])

### Matrix Operations in Pytorch

For the purposes of neural networks, perhaps the most important thing to know is how to perform matrix algebra operations.  Remember that the whole point of initializing a weight matrix and a bias vector is to use them to calculate the linear output of each neuron.

Let's initialize some data.

In [55]:
import numpy as np

X = torch.randn(3, 784)
X.shape

torch.Size([3, 784])

In [67]:
W1.shape, X.T.shape

(torch.Size([8, 784]), torch.Size([784, 3]))

In [81]:
W1 @ X.T 


tensor([[ -8.4259, -11.8295,  23.4698],
        [-39.4412,  36.8929, -61.9721],
        [-23.1415,  42.7091,  25.7792],
        [ 33.3887, -11.9642,  13.4949],
        [ 22.8652,   8.9591,  -3.2612],
        [ -9.7971,  17.3862, -10.0517],
        [ 12.3032, -52.7073,  32.4848],
        [ 19.9870,  23.3461,  -0.5489]])

So we can see above that we have eight outputs for each of our three observations, just like we saw before.

And to include the addition of a bias vector, we initialize a vector with eight rows.

In [82]:
b1 = torch.randn(8, 1)
b1

tensor([[-2.0904],
        [-1.2224],
        [-0.6987],
        [ 0.1317],
        [ 1.6392],
        [ 1.4074],
        [ 0.4002],
        [-0.1969]])

And then add.

In [87]:
Z1 = W1 @ X.T  + b1
Z1

tensor([[-10.5163, -13.9199,  21.3794],
        [-40.6635,  35.6705, -63.1945],
        [-23.8402,  42.0104,  25.0805],
        [ 33.5204, -11.8325,  13.6266],
        [ 24.5044,  10.5983,  -1.6220],
        [ -8.3896,  18.7937,  -8.6443],
        [ 12.7034, -52.3072,  32.8849],
        [ 19.7900,  23.1491,  -0.7459]])

So at this point, we can translate our `init_model` function to use Pytorch tensors.

In [90]:
def init_model(n_features, neur_l1, neur_out):
    W1 = torch.randn(n_features, neur_l1) / np.sqrt(n_features)
    b1 = torch.zeros((1, neur_l1))
    W2 = torch.randn(neur_l1, neur_out) / np.sqrt(neur_l1)
    b2 = torch.zeros((1, neur_out))
    model = {'W1': W1, 'b1': b1, 'W2': W2, 'b2': b2}
    return model

In [91]:
init_model(5, 3, 2)

{'W1': tensor([[ 0.2883,  0.5991,  0.0466],
         [-0.5802, -0.3250, -0.8185],
         [ 0.4495, -0.1099,  0.4779],
         [ 0.0704, -0.6322,  0.9711],
         [ 0.7418, -0.4575, -0.1500]]),
 'b1': tensor([[0., 0., 0.]]),
 'W2': tensor([[-0.0307, -0.4393],
         [-0.5518, -0.3604],
         [-0.3678, -0.2677]]),
 'b2': tensor([[0., 0.]])}

### Summary

In this lesson, we learned about initializing the weight matrices and bias vectors of our neural network with Pytorch tensors.  As we saw, Pytorch tensors are similar to numpy arrays both in their construction and the operations we can perform with them.

> We can initialize a Pytorch tensor in similar ways.

In [94]:
import torch

W1 = torch.randn(8, 784)

In [95]:
W1.shape

torch.Size([8, 784])

Use the `view` method to reshape the tensore.

In [96]:
W1.view(-1)

tensor([-0.2966, -0.7510,  0.9930,  ...,  1.9472, -0.3612,  0.0994])

And can perform matrix algebra operations with our tensor to pass our data through our linear layer.

In [97]:
Z1 = W1 @ X.T  + b1
Z1

tensor([[ 7.1926e+00,  2.8639e-03, -8.8633e+00],
        [ 4.1558e+01, -3.9941e+01, -3.0199e+01],
        [-1.3246e+01,  1.8456e+01,  2.3438e+01],
        [-3.0452e+01, -2.8885e+01, -2.9598e+01],
        [ 5.8378e+00, -4.2085e+01,  1.7439e+01],
        [-1.4112e+01, -2.5177e+00,  3.6517e+01],
        [-1.4192e+00, -3.1555e+01, -7.2901e+00],
        [ 2.5637e+01,  5.2545e+01,  1.7124e+01]])