# Autograd

In [2]:
import torch

t1 = torch.randn((3,3), requires_grad = True) 

In [5]:
import torch 

a = torch.randn((3,3), requires_grad = True)

w1 = torch.randn((3,3), requires_grad = True)
w2 = torch.randn((3,3), requires_grad = True)
w3 = torch.randn((3,3), requires_grad = True)
w4 = torch.randn((3,3), requires_grad = True)

In [34]:
b = w1*a 
c = w2*a

d = w3*b + w4*c

L = (10 - d).sum()

In [28]:
d.grad_fn

In [29]:
L.grad_fn

In [30]:
L.grad_fn.next_functions

((<AddBackward0 at 0x122236b90>, 0),)

In [35]:
L.backward()

<img src="./gradient-expl.png" width="60%">

> As you can see, the gradient to be backpropagated from a function f is basically:

* the gradient that is backpropagated to f from the layers in front of it
* multiplied by the local gradient of the output of f with respect to it's inputs. 

### More

### Linear Function

In [227]:
w = torch.tensor([2.01, 3.], requires_grad = True)
x = torch.tensor([4., 5.], requires_grad = True).T
b = torch.tensor([-3])
# (w @ x) + b

In [228]:
z = w @ x + b
z

tensor([20.0400], grad_fn=<AddBackward0>)

### Loss Function

In [233]:
y = torch.tensor(24., requires_grad = True)
l = (y - z) @ (y - z)
l
# w_1 = 2
# loss = 
# (16 - 15.6816)/.01

tensor(15.6816, grad_fn=<DotBackward>)

In [234]:
l.backward()

In [235]:
w.grad

tensor([-31.6800, -39.6000])

In [240]:
l.grad

In [64]:
y = torch.tensor([1., 2.], requires_grad = True)

In [65]:
y.backward(torch.tensor([2., 3.]))

In [238]:
w.grad/y.grad

tensor([-4., -5.])

In [242]:
z.grad

In [239]:
l.grad

### Resources

[Autograd paperspace](https://blog.paperspace.com/pytorch-101-understanding-graphs-and-automatic-differentiation/)